#ifndef game_h
#define game_h
#include "oop/user.h"
#include "oop/resource.h"
#include "oop/queue.h"
#include "utility/colour.h"
#include "utility/choice.h"
#include "minigame.h"
#include "ending.h"
#include <exception>
#include <math.h>
#define weekly update(player,money,happy,infect)
//#include "utility/print.h"
//#include "choice.h"
bool update(user&,resource &,resource &,resource &);
void print(resource &,resource &,resource &);
void savePhase(Q &);
void addDialog(Q &q,string,string="NULL");
int playPhase(user &,resource &,resource &,resource &,Q&,ii [],string []);
void game(user& player,ii highScore[],string leader[]);
bool update(user &player,resource &money,resource &happy,resource &infect)
{
    cout<<"=========*UPDATE*=========\n";
    player.addWeek();
    money.update();
    happy.update();
    infect.update();
    print(money,happy,infect);
    cout<<"==========================\n";
    //Sleep(500);
    return(!happy.check()||!money.check()||!infect.check());
}
void print(resource &money,resource &happy,resource &infect)
{
    money.print();
    happy.print();
    infect.print();
}
void savePhase(Q &q)
{
    cout<<"=========Your log=========\n";
    q.show();
    cout<<"==========================\n";
}
void addDialog(Q &q,string answer,string question)
{
    node *t=new node(question,answer);
    q.addNode(t);
    //cerr<<"add";

}
int playPhase(user &player,resource &money,resource &happy,resource &infect,Q &q,ii highScore[],string leader[])
{
    //cerr<<"play";
    Texture t[imgCount+1];
    inputTexture(t);
    RenderWindow win(VideoMode(843,789),"Game!");
    Sprite menu(t[1]);
    int score=0;
    string dialog[55];
    string way,x;
    inputDialog(dialog);
    if(win.isOpen())
    {
        bool com=0;
        Event e;
        win.draw(menu);
        win.display();
        while(!com)
        {
            Vector2i pos=Mouse::getPosition(win);
            Event e;
            while(win.pollEvent(e))
            {

                if(e.type==Event::Closed)
                {
                    win.close();
                    return 0;
                }
                if(e.type==Event::MouseButtonPressed)
                {
                    //cerr<<pos.x<<pos.y<<endl;
                    if(e.key.code==Mouse::Left)
                    {
                        if(pos.x>260&&pos.x<580&&pos.y>360&&pos.y<410)
                        {
                            com=1;
                            break;
                        }
                        if(pos.x>260&&pos.x<580&&pos.y>440&&pos.y<490)
                        {
                            readHighScore(highScore,leader);
                        }
                        if(pos.x>260&&pos.x<580&&pos.y>530&&pos.y<580)
                        {
                            win.close();
                            return 0;
                        }

                    }
                }

            }
        }
        addDialog(q,dialog[1]);
        print(dialog[1]);
        print(dialog[2]);
        displayScreen(win,t,2,3);
        displayScreen(win,t,4,5);
        displayScreen(win,t,4,6);
        displayScreen(win,t,7,8);
        displayScreen(win,t,9,10);
        displayScreen(win,t,9,11);
        displayScreen(win,t,12,13);
        displayScreen(win,t,14,15);
        displayScreen(win,t,16,17);
        displayScreen(win,t,16,18);
        displayScreen(win,t,19,20);
        displayScreen(win,t,19,21,0);
        happy.income(-28);
        if(choice(win,dialog[3],dialog[4]))
        {
            infect.income(0,-0.3);
            money.income(0,20);
            displayScreen(win,t,22,23);
            displayScreen(win,t,24,25);
            displayScreen(win,t,26,27);
            displayScreen(win,t,26,28);
            displayScreen(win,t,29,30);
            displayScreen(win,t,29,31);
            displayScreen(win,t,32,33,0);
            addDialog(q,dialog[2],dialog[3]);
            weekly;
            print(dialog[5]);
            if(choice(win,dialog[6],dialog[7]))
            {
                money.income(-100,-3);///////////
                addDialog(q,dialog[6]);
                weekly;
            }
            else
            {
                addDialog(q,dialog[7]);
                weekly;
            }
            print(dialog[9]);
            displayScreen(win,t,32,34);
            displayScreen(win,t,35,36);
            displayScreen(win,t,37,38);
            displayScreen(win,t,39,40);
            displayScreen(win,t,41,42);
            displayScreen(win,t,43,44);
            displayScreen(win,t,43,45,0);
            try
            {
                try
                {
                    if(choice(win,dialog[10],dialog[11]))
                    {
                        happy.income(-5);
                        money.income(0,-10);//////////
                        displayScreen(win,t,46,47);
                        displayScreen(win,t,46,48);
                        displayScreen(win,t,46,49);
                        displayScreen(win,t,46,50);
                        displayScreen(win,t,46,51);
                        displayScreen(win,t,46,52,0);
                        addDialog(q,dialog[10]);
                        weekly;
                        if(choice(win,dialog[12],dialog[13]))
                        {
                            throw 'A';
                        }
                        else
                        {
                            infect.income(0,-0.15);
                            happy.income(-5);
                            money.income(-750,-11);///////////
                            addDialog(q,dialog[13]);
                            weekly;
                            displayScreen(win,t,98,99);
                            displayScreen(win,t,98,100,0);
                            if(choice(win,dialog[12],dialog[18]))
                            {
                                money.income(400,6);////////////////balance
                                throw 'A';
                            }
                            else
                            {
                                infect.income(0,0.3);
                                happy.income(-10);
                                weekly;
                                addDialog(q,dialog[44],dialog[43]);
                                addDialog(q,dialog[45]);
                                print(dialog[46]);
                                happy.income(-20);
                                weekly;
                                throw int(4);
                                //////////////end(4)//////////////

                            }
                        }
                    }
                    else///////////state3
                    {
                        ////////infect////////////
                        infect.income(0,-0.3);
                        happy.income(-6);
                        money.income(0,-5);///////////////
                        addDialog(q,dialog[11]);
                        weekly;
                        displayScreen(win,t,92,93);
                        displayScreen(win,t,94,95);
                        displayScreen(win,t,96,97,0);
                        if(choice(win,dialog[47],dialog[53]))
                        {
                            happy.income(8);
                            displayScreen(win,t,108,109);
                            displayScreen(win,t,110,111,0);
                            if(choice(win,dialog[48],dialog[49]))
                            {
                                happy.income(4);
                                money.income(-1200,-13);///////////
                                addDialog(q,dialog[48],dialog[47]);
                                weekly;
                            }
                            else
                            {
                                happy.income(-2);
                                money.income(-425,-7);///////////
                                displayScreen(win,t,112,113);
                                displayScreen(win,t,114,115);
                                displayScreen(win,t,116,117,0);
                                addDialog(q,dialog[49],dialog[47]);
                                weekly;
                                print(dialog[50]);
                                if(choice(win,dialog[48],dialog[51]))
                                {
                                    happy.income(4);
                                    money.income(-1200,-13);///////////
                                    addDialog(q,dialog[48]);
                                }
                                else
                                {
                                    displayScreen(win,t,118,119);
                                    addDialog(q,dialog[51]);
                                }
                                weekly;
                            }
                        }
                        else
                        {
                            happy.income(4);
                            displayScreen(win,t,108,109);
                            displayScreen(win,t,110,111,0);
                            addDialog(q,dialog[52]);
                            weekly;
                            print(dialog[53]);
                            if(choice(win,dialog[48],dialog[49]))
                            {
                                happy.income(4);
                                money.income(-830,-12);//////////
                                displayScreen(win,t,112,113);
                                displayScreen(win,t,114,115);
                                displayScreen(win,t,116,117,0);
                                addDialog(q,dialog[48],dialog[53]);
                                weekly;
                            }
                            else
                            {
                                happy.income(-2);
                                money.income(-225,-6);////////////////
                                addDialog(q,dialog[49],dialog[53]);
                                weekly;
                                print(dialog[50]);

                                displayScreen(win,t,112,113);
                                displayScreen(win,t,114,115);
                                displayScreen(win,t,116,117,0);
                                if(choice(win,dialog[48],dialog[51]))
                                {
                                    happy.income(4);
                                    money.income(-830,-12);//////////
                                    addDialog(q,dialog[48]);
                                }
                                else
                                {
                                    displayScreen(win,t,118,119);
                                    addDialog(q,dialog[51]);
                                }
                                weekly;
                            }
                        }
                        displayScreen(win,t,120,121);
                        throw 'A';
                    }

                }
                catch(char)
                {
                    addDialog(q,dialog[12]);
                    print(dialog[12]);
                    infect.income(0,-0.3);
                    happy.income(1);
                    money.income(-100);
                    weekly;
                    displayScreen(win,t,53,54);
                    displayScreen(win,t,55,56);
                    displayScreen(win,t,55,57);
                    displayScreen(win,t,55,58,0);
                    if(choice(win,dialog[14],dialog[15]))
                    {
                        money.income(-150,-5);//faster but more expensive
                        weekly;
                        print(dialog[16]);
                        money.income(-750,-11);//////////
                        weekly;
                        addDialog(q,dialog[14]);
                        addDialog(q,dialog[16]);
                        way="I";
                    }
                    else
                    {
                        weekly;
                        print(dialog[17]);
                        money.income(-750,-11);//////////
                        weekly;
                        addDialog(q,dialog[15]);
                        addDialog(q,dialog[17]);
                        way="II";
                    }
                    displayScreen(win,t,59,60);
                    displayScreen(win,t,61,62);
                    displayScreen(win,t,63,64);
                    displayScreen(win,t,63,65);
                    displayScreen(win,t,66,67,0);
                    if(choice(win,dialog[19],dialog[20]))
                    {
                        infect.income(0,-0.3);
                        money.income(-125,-4);/////////////
                        addDialog(q,dialog[19]);
                    }
                    else
                    {
                        infect.income(0,-0.15);
                        happy.income(-4);
                        money.income(-350,-8);//////////////
                        addDialog(q,dialog[20]);
                    }
                    weekly;
                    print(dialog[21]);
                }
                displayScreen(win,t,68,69);
                displayScreen(win,t,70,71);
                displayScreen(win,t,72,73);
                displayScreen(win,t,72,74);
                displayScreen(win,t,75,76);
                displayScreen(win,t,77,78,0);
                if(choice(win,dialog[22],dialog[23]))
                {
                    infect.income(0,-0.15);
                    displayScreen(win,t,79,80);
                    displayScreen(win,t,81,82);
                    displayScreen(win,t,81,83);
                    displayScreen(win,t,84,85,0);
                    weekly;
                    addDialog(q,dialog[22],dialog[21]);
                    if(choice(win,dialog[24],dialog[26]))
                    {
                        print(dialog[25]);
                        weekly;
                        displayScreen(win,t,86,87);
                        displayScreen(win,t,86,88);
                        displayScreen(win,t,86,89);
                    }
                    print(dialog[26]);
                    addDialog(q,dialog[26]);
                    money.income(500,-9);////////////////
                    weekly;
                }
                else
                {
                    addDialog(q,dialog[23],dialog[21]);
                    print(dialog[27]);
                    happy.income(-6);
                    money.income(-10,-1);///////////////
                    weekly;
                    displayScreen(win,t,101,102);
                    displayScreen(win,t,101,103,0);
                    if(!choice(win,dialog[31],dialog[28]))
                    {
                        infect.income(0,0.3);
                        displayScreen(win,t,106,107);
                        addDialog(q,dialog[28],dialog[27]);
                        happy.income(-32);
                        weekly;
                        print(dialog[29]);
                        addDialog(q,dialog[29]);
                        throw int(5);
                    }
                    else
                    {
                        displayScreen(win,t,104,105);
                        displayScreen(win,t,79,80);
                        displayScreen(win,t,81,82);
                        displayScreen(win,t,81,83);
                        displayScreen(win,t,84,85,0);
                        addDialog(q,dialog[31],dialog[27]);
                        happy.income(4);
                        money.income(-50,-2);///////////////
                        weekly;
                        print(dialog[32]);
                        addDialog(q,dialog[32]);
                        weekly;
                        if(choice(win,dialog[33],dialog[34]))
                        {
                            happy.income(12);
                            money.income(250,-7);/////////////
                            addDialog(q,dialog[33]);
                            weekly;
                        }
                        else
                        {
                            happy.income(6);
                            money.income(500,-9);///////////////
                            addDialog(q,dialog[34]);
                            weekly;
                        }
                    }
                }
                displayScreen(win,t,90,91);
                displayScreen(win,t,92,93);
                displayScreen(win,t,94,95);
                displayScreen(win,t,96,97,0);
                addDialog(q,dialog[11]);
                weekly;
                if(choice(win,dialog[47],dialog[53]))
                {
                    happy.income(8);
                    displayScreen(win,t,108,109);
                    displayScreen(win,t,110,111,0);
                    if(choice(win,dialog[48],dialog[49]))
                    {
                        happy.income(4);
                        money.income(-1200,-13);//////////
                        addDialog(q,dialog[48],dialog[47]);
                        weekly;
                    }
                    else
                    {
                        displayScreen(win,t,112,113);
                        displayScreen(win,t,114,115);
                        displayScreen(win,t,116,117,0);
                        addDialog(q,dialog[49],dialog[47]);
                        happy.income(-2);
                        money.income(-425,-7);
                        weekly;
                        print(dialog[50]);
                        if(choice(win,dialog[48],dialog[51]))
                        {
                            happy.income(4);
                            money.income(-1200,-13);//////////
                            addDialog(q,dialog[48]);
                        }
                        else
                        {
                            displayScreen(win,t,118,119);
                            addDialog(q,dialog[51]);
                        }
                        weekly;
                    }
                }
                else
                {
                    displayScreen(win,t,108,109);
                    displayScreen(win,t,110,111,0);
                    addDialog(q,dialog[52]);
                    happy.income(4);
                    weekly;
                    print(dialog[53]);
                    if(choice(win,dialog[48],dialog[49]))
                    {
                        displayScreen(win,t,112,113);
                        displayScreen(win,t,114,115);
                        displayScreen(win,t,116,117,0);
                        addDialog(q,dialog[48],dialog[53]);
                        happy.income(4);
                        money.income(-830,-12);////////////
                        weekly;
                    }
                    else
                    {
                        happy.income(-2);
                        money.income(-255,-6);//////////
                        addDialog(q,dialog[49],dialog[53]);
                        weekly;
                        print(dialog[50]);

                        displayScreen(win,t,112,113);
                        displayScreen(win,t,114,115);
                        displayScreen(win,t,116,117,0);
                        if(choice(win,dialog[48],dialog[51]))
                        {

                            happy.income(4);
                            money.income(-830,-12);////////////
                            addDialog(q,dialog[48]);
                        }
                        else
                        {
                            displayScreen(win,t,118,119);
                            addDialog(q,dialog[51]);
                        }
                        weekly;
                    }
                }
                displayScreen(win,t,120,121);

                if(way=="I")
                    throw int(1);
                if(way=="II")
                    throw int(2);
            }
            catch(int x)
            {
                if(x==4||x==5)
                {
                    print(dialog[30]);
                    addDialog(q,dialog[30]);
                    ending(win,x);
                }
                else
                {
                    bool bonus=minigame(score);
                    if(bonus)
                    {
                        print(dialog[36]);
                        happy.income(12);
                        weekly;
                        addDialog(q,dialog[36]);
                        addDialog(q,dialog[37]);
                        ending(win,1);
                        print(dialog[37]);
                    }
                    else
                    {
                        if(x==1)
                        {
                            print(dialog[38]);
                            weekly;
                            print(dialog[39]);
                            happy.income(6);
                            weekly;
                            print(dialog[40]);
                            addDialog(q,dialog[38]);
                            addDialog(q,dialog[39]);
                            addDialog(q,dialog[40]);
                            ending(win,2);
                        }
                        if(x==2)
                        {
                            print(dialog[42]);
                            happy.income(-24);
                            weekly;
                            print(dialog[30]);
                            addDialog(q,dialog[42]);
                            addDialog(q,dialog[30]);
                            ending(win,3);
                        }
                    }
                }
            }
            catch(...)
            {
                cout<<"exception remain\n";
            }
        }
        else ////////////////////////////////////////////////////////////////
        {
            addDialog(q,dialog[4],dialog[2]);
            weekly;
            print(dialog[54]);
            displayScreen(win,t,68,69);
            displayScreen(win,t,70,71);
            displayScreen(win,t,72,73);
            displayScreen(win,t,72,74);
            displayScreen(win,t,75,76);
            displayScreen(win,t,77,78,0);
            if(choice(win,dialog[22],dialog[23]))
            {
                infect.income(0,-0.15);
                addDialog(q,dialog[22],dialog[54]);
                weekly;
                displayScreen(win,t,79,80);
                displayScreen(win,t,81,82);
                displayScreen(win,t,81,83);
                displayScreen(win,t,84,85,0);
                if(choice(win,dialog[24],dialog[26]))
                {
                    addDialog(q,dialog[24]);
                    weekly;
                    print(dialog[25]);
                    addDialog(q,dialog[25]);
                    displayScreen(win,t,86,87);
                    displayScreen(win,t,86,88);
                    displayScreen(win,t,86,89);
                }
                print(dialog[26]);
                money.income(500,-9);////////////
                weekly;
                addDialog(q,dialog[26]);
            }
            else
            {
                addDialog(q,dialog[23],dialog[54]);
                happy.income(-6);
                money.income(-10,-1);//////////////
                weekly;
                displayScreen(win,t,79,80);
                displayScreen(win,t,81,82);
                displayScreen(win,t,81,83);
                displayScreen(win,t,84,85,0);
                if(choice(win,dialog[24],dialog[26]))
                {
                    happy.income(12);
                    money.income(250,-7);////////////
                    addDialog(q,dialog[24]);
                }
                else
                {
                    happy.income(6);
                    money.income(500,-9);/////////////
                    addDialog(q,dialog[26]);
                }
                weekly;
            }

            happy.income(4);
            weekly;
            displayScreen(win,t,90,91);
            displayScreen(win,t,92,93);
            displayScreen(win,t,94,95);
            displayScreen(win,t,96,97,0);
            addDialog(q,dialog[11]);
            if(choice(win,dialog[47],dialog[53]))
            {
                happy.income(8);
                displayScreen(win,t,108,109);
                displayScreen(win,t,110,111,0);
                if(choice(win,dialog[48],dialog[49]))
                {
                    happy.income(4);
                    money.income(-1200,-13);//////////////
                    addDialog(q,dialog[48],dialog[47]);
                    weekly;
                }
                else
                {
                    happy.income(-2);
                    money.income(-425,-7);//////////////
                    displayScreen(win,t,112,113);
                    displayScreen(win,t,114,115);
                    displayScreen(win,t,116,117,0);
                    addDialog(q,dialog[49],dialog[47]);
                    weekly;
                    print(dialog[50]);
                    if(choice(win,dialog[48],dialog[51]))
                    {
                        happy.income(4);
                        money.income(-1200,-13);//////////////
                        addDialog(q,dialog[48]);
                    }
                    else
                    {
                        displayScreen(win,t,118,119);
                        addDialog(q,dialog[51]);
                    }
                    weekly;
                }
            }
            else
            {
                happy.income(4);
                displayScreen(win,t,108,109);
                displayScreen(win,t,110,111,0);
                addDialog(q,dialog[52]);
                weekly;
                print(dialog[53]);
                if(choice(win,dialog[48],dialog[49]))
                {
                    happy.income(4);
                    money.income(-830,-11);//////////////
                    displayScreen(win,t,112,113);
                    displayScreen(win,t,114,115);
                    displayScreen(win,t,116,117,0);
                    addDialog(q,dialog[48],dialog[53]);
                    weekly;
                }
                else
                {
                    happy.income(-2);
                    money.income(-225,-6);//////////////
                    addDialog(q,dialog[49],dialog[53]);
                    weekly;
                    print(dialog[50]);

                    displayScreen(win,t,112,113);
                    displayScreen(win,t,114,115);
                    displayScreen(win,t,116,117,0);
                    if(choice(win,dialog[48],dialog[51]))
                    {
                        happy.income(4);
                        money.income(-830,-11);//////////////
                        addDialog(q,dialog[48]);
                    }
                    else
                    {
                        displayScreen(win,t,118,119);
                        addDialog(q,dialog[51]);
                    }
                    weekly;
                }
            }
            displayScreen(win,t,120,121);

            //
            /////////////////////////////after bug////////////////////////////////
            addDialog(q,dialog[3]);
            addDialog(q,dialog[5]);
            infect.income(0,-0.3);
            print(dialog[3]);
            weekly;
            print(dialog[5]);
            displayScreen(win,t,22,23);
            displayScreen(win,t,24,25);
            displayScreen(win,t,26,27);
            displayScreen(win,t,26,28);
            displayScreen(win,t,29,30);
            displayScreen(win,t,29,31);
            displayScreen(win,t,32,33,0);
            if(choice(win,dialog[6],dialog[7]))
            {
                money.income(-100,-3);///////////
                addDialog(q,dialog[6]);
                weekly;
            }
            else
            {
                addDialog(q,dialog[7]);
                addDialog(q,dialog[8]);
                weekly;

            }
            displayScreen(win,t,32,34);
            //
            displayScreen(win,t,46,47);
            displayScreen(win,t,46,48);
            displayScreen(win,t,46,49);
            displayScreen(win,t,46,50);
            displayScreen(win,t,46,51);
            displayScreen(win,t,46,52,0);
            if(!choice(win,dialog[12],dialog[13]))
            {
                infect.income(0,-0.15);
                addDialog(q,dialog[13]);
                happy.income(-5);
                money.income(-750,-11);/////////////
                weekly;
                displayScreen(win,t,98,99);
                displayScreen(win,t,98,100,0);
                if(!choice(win,dialog[12],dialog[18]))
                {
                    infect.income(0,0.3);
                    addDialog(q,dialog[44],dialog[43]);
                    addDialog(q,dialog[45]);
                    addDialog(q,dialog[46]);
                    happy.income(-10);
                    weekly;
                    print(dialog[45]);
                    happy.income(-20);
                    weekly;
                    print(dialog[46]);
                    way="III";

                }
                else
                {
                    money.income(400,6);
                }
            }
            if(way!="III")
            {
                ///////////infect/////
                print(dialog[12]);
                infect.income(0,-0.3);
                happy.income(1);
                money.income(-100);//////////////
                weekly;
                addDialog(q,dialog[12]);
                displayScreen(win,t,53,54);
                displayScreen(win,t,55,56);
                displayScreen(win,t,55,57);
                displayScreen(win,t,55,58,0);
                if(choice(win,dialog[14],dialog[15]))
                {
                    money.income(-150,5);//faster but more expensive
                    weekly;
                    print(dialog[16]);
                    weekly;
                    addDialog(q,dialog[14]);
                    addDialog(q,dialog[16]);
                    way="I";
                }
                else
                {
                    weekly;
                    print(dialog[17]);
                    weekly;
                    addDialog(q,dialog[15]);
                    addDialog(q,dialog[17]);
                    way="II";
                }
                money.income(-750,-11);//////////////
                displayScreen(win,t,59,60);
                displayScreen(win,t,61,62);
                displayScreen(win,t,63,64);
                displayScreen(win,t,63,65);
                displayScreen(win,t,66,67,0);
                if(choice(win,dialog[19],dialog[20]))
                {
                    infect.income(0,-0.3);
                    money.income(-125,-4);/////////
                    addDialog(q,dialog[19]);
                }
                else
                {
                    infect.income(0,-0.15);
                    happy.income(-4);
                    money.income(-350,-8);
                    addDialog(q,dialog[20]);
                }
                weekly;
                print(dialog[21]);
                weekly;
                print(dialog[32]);
                weekly;
                print(dialog[35]);
                addDialog(q,dialog[21]);
                addDialog(q,dialog[32]);
                addDialog(q,dialog[35]);
            }

            int score;
            if(way=="III")
            {
                ending(win,4);
            }
            else
            {
                bool bonus=minigame(score);
                if(bonus)
                {
                    print(dialog[36]);
                    happy.income(12);
                    weekly;
                    print(dialog[37]);
                    addDialog(q,dialog[36]);
                    addDialog(q,dialog[37]);
                    ending(win,1);
                }
                else
                {
                    if(way=="I")
                    {
                        print(dialog[38]);
                        weekly;
                        print(dialog[39]);
                        happy.income(6);
                        weekly;
                        print(dialog[40]);
                        addDialog(q,dialog[38]);
                        addDialog(q,dialog[39]);
                        addDialog(q,dialog[40]);
                        ending(win,2);
                    }
                    else
                    {
                        happy.income(-24);
                        print(dialog[42]);
                        weekly;
                        print(dialog[30]);
                        addDialog(q,dialog[42]);
                        addDialog(q,dialog[30]);
                        ending(win,3);
                    }

                }
            }
        }
    }
    win.close();
    return score;
}
void game(user& player,ii highScore[],string leader[])
{
    //setd();
    resource money("money",4500,10);
    resource happy("happy",100);
    resource infect("infect",1,2.6);
    Q q;
    int score=playPhase(player,money,happy,infect,q,highScore,leader);
    score+=happy.getAmount()*100;
    score-=log(infect.getAmount())*10;
    score+=log(money.getAmount())*300;
    savePhase(q);
    player.setScore(score);
}



#endif
